### ISSUE TITLE
On adding new TODO, the search 🔍 bar should get cleared.

### ISSUE THREAD

**Issue by PriyansuMaurya** [slim-codes/todo#14]
### Description

This is how it normally looks 
![image](https://user-images.githubusercontent.com/101447544/194602939-43447fca-c6b1-4a23-823f-a908d45a7ecf.png)

 This is how it looks after adding `"Coding"` TODO but the text is still in the input box.

![image](https://user-images.githubusercontent.com/101447544/194603118-b6726df4-1699-49ba-94c6-f69f1680f0ab.png)

This is how it should look like after adding `"Coding" ` TODO.
![image](https://user-images.githubusercontent.com/101447544/194603274-ed81c58e-6544-4b25-900a-65667abb6050.png)

**Comment by slim-codes** [comment]
Great idea!.
Would you like to fix it?

**Comment by PriyansuMaurya** [comment]
Well, I don't know how to deal with angular but I would like to give it a try in coming days.

**Comment by SafalKoirala** [comment]
I can fix this.

**Comment by slim-codes** [comment]
@SafalKoirala 
What's your status? I understand that you're not familiar with Angular. Hence, if you are not able to fix it let me know so that I will assign it to someone else

**Comment by PriyansuMaurya** [comment]
Yeah Go forward, I mean assign it to anybody who is interested.

**Comment by slim-codes** [comment]
Alright then
@SafalKoirala You can go ahead
