### ISSUE TITLE
DOCS: Improve Contributing.md file

### ISSUE THREAD

**Issue by slim-codes** [slim-codes/todo#9]
### Description

Presently, the instructions for contributing to this project are vague and short.

- Improve the contributing.md file

**Comment by slim-codes** [comment]
Improve CONTRIBUTING.md file. It is not comprehensive and lacks detail

**Comment by AdarshCoder397** [comment]
Hey @slim-codes , I can work on this!!

**Comment by cmarchena** [comment]
Hi @slim-codes you have closed my PR without merging and without explaining why

**Comment by cmarchena** [comment]
Ok, it seems you have been struggling with this issue for a long time, I guess is better you write it yourself instead of proposing collaboration.
Kind regards and good luck!
